drop table if exists identity_auditevent;
drop table if exists identity_identitysession;
drop table if exists identity_hrmemployeelink;
drop table if exists identity_directgrant;
drop table if exists identity_rolepermission;
drop table if exists identity_applicationassignment;
drop table if exists identity_application;
drop table if exists identity_permission;
drop table if exists identity_membershiprole;
drop table if exists identity_role;
drop table if exists identity_membership;
drop table if exists identity_tenant;
drop table if exists identity_user;

create table identity_user (
    id uuid primary key,
    password varchar(128) not null default '',
    last_login timestamp null,
    is_superuser boolean not null default false,
    email varchar(254) not null unique,
    display_name varchar(160) not null,
    is_active boolean not null default true,
    is_staff boolean not null default false,
    ory_id uuid null,
    security_version integer not null default 1,
    created_at timestamp not null,
    updated_at timestamp not null
);

create table identity_tenant (
    id uuid primary key,
    slug varchar(80) not null unique,
    name varchar(160) not null,
    status varchar(16) not null default 'active',
    require_mfa boolean not null default false,
    session_max_days integer not null default 7,
    created_at timestamp not null
);

create table identity_membership (
    id uuid primary key,
    tenant_id uuid not null,
    user_id uuid not null,
    department varchar(120) not null default '',
    title varchar(120) not null default '',
    status varchar(16) not null default 'active',
    policy_version integer not null default 1,
    created_at timestamp not null,
    updated_at timestamp not null
);

create table identity_role (
    id uuid primary key,
    tenant_id uuid null,
    code varchar(60) not null,
    name varchar(100) not null,
    description varchar(300) not null default '',
    is_system boolean not null default false,
    created_at timestamp not null
);

create table identity_permission (
    id uuid primary key,
    code varchar(120) not null unique,
    name varchar(160) not null default '',
    description varchar(300) not null default '',
    created_at timestamp not null
);

create table identity_membershiprole (
    id bigint generated by default as identity primary key,
    membership_id uuid not null,
    role_id uuid not null,
    assigned_by_id uuid null,
    created_at timestamp not null
);

create table identity_rolepermission (
    id bigint generated by default as identity primary key,
    role_id uuid not null,
    permission_id uuid not null
);

create table identity_directgrant (
    id bigint generated by default as identity primary key,
    membership_id uuid not null,
    permission_id uuid not null,
    allowed boolean not null default true,
    created_at timestamp not null
);

create table identity_application (
    id uuid primary key,
    tenant_id uuid null,
    client_id varchar(80) not null unique,
    name varchar(120) not null,
    slug varchar(80) not null,
    description varchar(300) not null default '',
    application_type varchar(20) not null default 'internal',
    redirect_uris clob not null,
    allowed_scopes clob not null,
    required_permissions clob not null,
    icon varchar(48) not null default 'squares-2x2',
    client_secret_hash varchar(128) not null default '',
    is_public boolean not null default false,
    is_active boolean not null default true,
    created_at timestamp not null,
    updated_at timestamp not null
);

create table identity_applicationassignment (
    id bigint generated by default as identity primary key,
    membership_id uuid not null,
    application_id uuid not null,
    is_enabled boolean not null default true,
    last_accessed_at timestamp null,
    created_at timestamp not null
);

create table identity_identitysession (
    id uuid primary key,
    user_agent varchar(600) not null default '',
    ip_hash varchar(64) not null default '',
    location varchar(120) not null default '',
    authentication_methods clob not null,
    auth_time timestamp not null,
    last_seen_at timestamp not null,
    expires_at timestamp not null,
    revoked_at timestamp null,
    revoked_reason varchar(80) not null default '',
    user_id uuid not null,
    tenant_id uuid not null,
    security_version integer not null default 1,
    kratos_session_id uuid null,
    hydra_sid uuid null
);

create table identity_hrmemployeelink (
    id uuid primary key,
    tenant_id uuid not null,
    user_id uuid not null,
    membership_id uuid not null,
    employee_id uuid not null,
    employee_code varchar(40) not null,
    status varchar(16) not null default 'active',
    source varchar(64) not null default 'manual',
    created_at timestamp not null,
    updated_at timestamp not null
);

create table identity_auditevent (
    id uuid primary key,
    tenant_id uuid null,
    actor_id uuid null,
    action varchar(120) not null,
    target_type varchar(80) not null default '',
    target_id varchar(128) not null default '',
    outcome varchar(20) not null default 'success',
    ip_hash varchar(64) not null default '',
    user_agent varchar(600) not null default '',
    correlation_id uuid not null,
    metadata clob not null,
    previous_hash varchar(64) not null default '',
    event_hash varchar(64) not null unique,
    created_at timestamp not null
);
