create table if not exists leads_lead (
    id bigint generated by default as identity primary key,
    name varchar(120) not null,
    email varchar(254) not null,
    company varchar(180) not null,
    message text not null,
    phone varchar(32) not null default '',
    locale varchar(5) not null default 'vi',
    consent boolean not null default false,
    source_url varchar(500) not null default '',
    utm_source varchar(120) not null default '',
    utm_medium varchar(120) not null default '',
    utm_campaign varchar(200) not null default '',
    status varchar(16) not null default 'new',
    owner_id uuid null,
    assigned_at timestamptz null,
    idempotency_key varchar(64) not null unique,
    spam_score double precision not null default 0,
    created_at timestamptz not null
);

create index if not exists leads_lead_status_8a7a_idx
    on leads_lead (status, created_at);

create index if not exists leads_lead_email_idx
    on leads_lead (email);

create index if not exists leads_lead_owner_idx
    on leads_lead (owner_id);

create table if not exists leads_leadactivity (
    id bigint generated by default as identity primary key,
    lead_id bigint not null,
    actor_id uuid null,
    action varchar(16) not null,
    payload jsonb not null default '{}'::jsonb,
    created_at timestamptz not null
);

create index if not exists leads_leadact_lead_created_idx
    on leads_leadactivity (lead_id, created_at);

create table if not exists outbox_events (
    id uuid primary key,
    tenant_id uuid not null,
    event_type text not null,
    aggregate_type text not null,
    aggregate_id uuid not null,
    payload jsonb not null,
    headers jsonb not null,
    occurred_at timestamptz not null,
    published_at timestamptz null,
    attempt_count integer not null default 0,
    available_at timestamptz not null,
    created_at timestamptz not null
);

create index if not exists idx_outbox_pub_occ
    on outbox_events (published_at, occurred_at);

create index if not exists idx_outbox_agg_id
    on outbox_events (aggregate_type, aggregate_id);
