# Generated by Django 5.1.8 on 2026-08-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="keycloak_id",
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
